name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - pandas=2.0.0
  - pip=23.1
  - scikit-learn=1.0.2
  - matplotlib=3.7.1
  - plotly=5.14.1
  - pillow=9.5.0
  - mlflow=1.26.1
  - pip:
      - wandb==0.15.0
